# Generated by Django 5.0.7 on 2024-07-31 12:43

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_rtchat", "0008_alter_groupmessage_options_groupmessage_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupmessage",
            options={},
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="body",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
